/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-120041-g64fce7202c-20250626"
#endif /* AVUTIL_FFVERSION_H */
